### ISSUE TITLE
an error occurs during execution

### ISSUE THREAD

**Issue by yangxuan74** [CentOS/8docs#3]
I get an error when I execute the following command
`$ ./build.sh && ./preview.sh`
The error message is as follows:
```
This build script is using Podman to run the build in an isolated environment.

error: Failed to download UI bundle: http://file.brq.redhat.com/~pbokoc/ui-bundle.zip
Add the --stacktrace option to see the cause.

```
How to solve this problem?

**Comment by pbokoc** [comment]
Oops, that's my bad, I must have accidentally committed a testing config. Pull and try again, it should work now.
